CREATE TABLE ROLES
(
    ID        INT          NOT NULL AUTO_INCREMENT,
    ROLE_NAME VARCHAR(128) NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE PERMISSION_ROLES
(
    FK_ROLE_ID      INT          NOT NULL,
    PERMISSION_NAME VARCHAR(256) NOT NULL,

    FOREIGN KEY (FK_ROLE_ID) REFERENCES ROLES (ID)
);

CREATE TABLE USERS
(
    ID         INT          NOT NULL AUTO_INCREMENT,
    USER_NAME  VARCHAR(128) NOT NULL UNIQUE,
    PASSWORD   VARCHAR(256) NOT NULL,
    FK_ROLE_ID INT          NOT NULL,
    SUPER_USER INT          NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (FK_ROLE_ID) REFERENCES ROLES (ID)
);