INSERT INTO ROLES (ROLE_NAME)
VALUES ('ADMIN');
INSERT INTO PERMISSION_ROLES (FK_ROLE_ID, PERMISSION_NAME)
SELECT ID, 'CREATE_USER' FROM ROLES WHERE ROLE_NAME = 'ADMIN';
INSERT INTO PERMISSION_ROLES (FK_ROLE_ID, PERMISSION_NAME)
SELECT ID, 'UPDATE_USER' FROM ROLES WHERE ROLE_NAME = 'ADMIN';
INSERT INTO PERMISSION_ROLES (FK_ROLE_ID, PERMISSION_NAME)
SELECT ID, 'DELETE_USER' FROM ROLES WHERE ROLE_NAME = 'ADMIN';
INSERT INTO PERMISSION_ROLES (FK_ROLE_ID, PERMISSION_NAME)
SELECT ID, 'LIST_USERS' FROM ROLES WHERE ROLE_NAME = 'ADMIN';

INSERT INTO USERS(USER_NAME, PASSWORD, SUPER_USER ,FK_ROLE_ID)
SELECT 'Admin', MD5('password'), 1 ,ID FROM ROLES WHERE ROLE_NAME = 'ADMIN';